backend: 
  repo: ericmikkelsen/19
  name: git-gateway
publish_mode: editorial_workflow
media_folder: uploads # Media files will be stored in the repo under images/uploads
public_folder: /images/uploads
collections:
  - name: provider # Used in routes, e.g., /admin/collections/blog
    label: Health Provider # Used in the UI
    folder: providers/{{fields.zip}} # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{fields.zip}}/{{slug}}/" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Provider URL", name: "provider_url", widget: "string", required: false }
      - { label: "Street Address", name: "address",widget: "string" }
      - { label: "Unit number", name: "unit", widget: "string", required: false }
      - { label: "City or Town", name: "city", widget: "string"} 
      - { label: "State", name: "state", widget: "string"} 
      - { label: "Zip", name: "zip", widget: number}
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Phone Number", name: "phone", widget: "number", required: false }
      - { label: "Fax", name: "fax", widget: "number", required: false }
      - { label: "Twitter", name: "twitter", widget: "string", required: false }
      - { label: "Facebook", name: "facebook", widget: "string", required: false }
      - { label: "Upload", name: "upload", widget: "string", required: false }